### ISSUE TITLE
Improve code coverage

### ISSUE THREAD

**Issue by tosan88** [Financial-Times/upp-next-video-mapper#20]
Currently is 64.471%, see https://coveralls.io/github/Financial-Times/next-video-mapper?branch=master

**Comment by PlamenHristov** [comment]
@tosan88, this is the output from go coverage
`phristov@phristov:~/ft/src/github.com/Financial-Times/upp-next-video-mapper$ go test -cover ./video/...
ok      github.com/Financial-Times/upp-next-video-mapper/video  0.004s  coverage: 76.2% of statements`
I read that it's recommended for the test coverage to be 75%. 
Do we want to increase it more and be how much ?

**Comment by yolandeleungFT** [comment]
@PlamenHristov The metrics that @tosan88 was referring to are the Coveralls stats.
https://coveralls.io/builds/19247431

**Comment by emildimitrov** [comment]
Coverage improved
